// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP0Rt61jW0BXzeWG_8k_bUFXh9ER57x1k',
    appId: '1:704336011311:web:6dd03ec31c68a8d25ce6da',
    messagingSenderId: '704336011311',
    projectId: 'calendo-5ab41',
    authDomain: 'calendo-5ab41.firebaseapp.com',
    storageBucket: 'calendo-5ab41.appspot.com',
    measurementId: 'G-8VXQJGH3P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkBgpDg_ydOZ05KnNJbX217loWsX6ZBeI',
    appId: '1:704336011311:android:7696b7904c8496635ce6da',
    messagingSenderId: '704336011311',
    projectId: 'calendo-5ab41',
    storageBucket: 'calendo-5ab41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbP0z6xciekXGX_zfOduIUYNEQnZeVdY',
    appId: '1:704336011311:ios:50170dd5cb102a675ce6da',
    messagingSenderId: '704336011311',
    projectId: 'calendo-5ab41',
    storageBucket: 'calendo-5ab41.appspot.com',
    iosBundleId: 'com.example.calenDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbP0z6xciekXGX_zfOduIUYNEQnZeVdY',
    appId: '1:704336011311:ios:50170dd5cb102a675ce6da',
    messagingSenderId: '704336011311',
    projectId: 'calendo-5ab41',
    storageBucket: 'calendo-5ab41.appspot.com',
    iosBundleId: 'com.example.calenDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP0Rt61jW0BXzeWG_8k_bUFXh9ER57x1k',
    appId: '1:704336011311:web:57de2d974af68f7b5ce6da',
    messagingSenderId: '704336011311',
    projectId: 'calendo-5ab41',
    authDomain: 'calendo-5ab41.firebaseapp.com',
    storageBucket: 'calendo-5ab41.appspot.com',
    measurementId: 'G-TZJWM20C5W',
  );
}
